### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by xtrasmal** [vespakoen/menu#100]
Is there or will there be support for named routes?

**Comment by mouhsinelonly** [comment]
+1

**Comment by Luceos** [comment]
+1

**Comment by vespakoen** [comment]
Can you elaborate on what this would look like?
Are you aware that you can name an itemlist?
Menu::items('name-of-list')

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!

**Comment by vespakoen** [comment]
Oh I think I see what you mean, are you guys aware of the "route" helper?

```
$menu->addLink(route('profile'), ...); // should do the trick
```
