### ISSUE TITLE
Looking for a basic demo

### ISSUE THREAD

**Issue by illuminate3** [vespakoen/menu#103]
Hi,

I was wondering if anybody has an example of how they implemented this?
I'm especially looking for the front-end rather than the backend since I sort of have that working...

**Comment by younes0** [comment]
I agree that documentation lacks of a clean & real example:

```php
$menu = Menu::handler('mailbox'); 

// items
$menu
    ->add('contacts', 'Contacts')
    ->add('inbox', 'Inbox')
    ->add('folders', 'Folders', Menu::items() 
        ->prefixParents() 
        ->add('urgent', 'Urgent') // with prefix: /folders/urgent
        ->add('sent', 'Sent')
        ->add('deleted', 'Deleted')
    );

// styling
$menu
    ->addClass('nav navbar-nav')
    ->getItemsByContentType(Menu\Items\Contents\Link::class)
    ->map(function($item) {
        if ( $item->isActive() )  {
            $item->addClass('active');
        }
    });
```

`{!! $menu->render() !!}` will output:

```html
<ul class="nav navbar-nav">
  <li class="active"> <!-- current element in laravel, detected by library -->
    <a href="http://myapp.com/contacts">Contacts</a>
  </li>
  <li>
    <a href="http://myapp.com/inbox">Inbox</a>
  </li>
  <li>
    <a href="http://myapp.com/folders">Folders</a>
    <ul>
      <li>
        <a href="http://myapp.com/folders/urgent">Urgent</a>
      </li>
      <li>
        <a href="http://myapp.com/folders/sent">Sent</a>
      </li>
      <li>
        <a href="http://myapp.com/folders/deleted">Deleted</a>
      </li>
    </ul>
  </li>
</ul>
```

**Comment by illuminate3** [comment]
That helps. Thanks!

I was hoping for an implementation that pulls data from the database though.

**Comment by vespakoen** [comment]
You can use the hydrate method for that:

```php
$pages = Page::where('group', '=', 'main')->get();

$addItem = function($children, $item) {
  $children->add($item->slug, $item->name, Menu::items($item->slug));
};

Menu::handler('main')->hydrate($pages, $addItem, 'id', 'parent_id');
```

Hope it's self explanatory, if not, let me know.

**Comment by illuminate3** [comment]
Putting this here since it's relevant:
https://github.com/vespakoen/menu/issues/74

That helped. Thanks.


Next up:
Looking for a decent vertical CSS, if anybody has some to share :smile:

**Comment by vespakoen** [comment]
Assuming this can be closed.

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
