### ISSUE TITLE
Menu editing.

### ISSUE THREAD

**Issue by berpcor** [vespakoen/menu#106]
Hello.
I have menu:

item1
item2
-sub1
-sub2
-sub3
item3

I need to move all subs from item2 to item1.
How can I do that?

**Comment by abilondias** [comment]
Hello @berpcor, where's your code?

**Comment by vespakoen** [comment]
Closing this, if you still need help on it, let me know.

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!

**Comment by vespakoen** [comment]
FYI:

Check out the `getChildren` that Item's have (which comes from all the way up here: https://github.com/Anahkiasen/html-object/blob/c5c95e74524a5f65700a3eb6e1211ebeacf3c9aa/src/Traits/TreeObject.php#L145)

And the `attach` method on the ItemList http://vespakoen.github.io/menu/class-Menu.Items.ItemList.html#_attach
