### ISSUE TITLE
Hydrate empty/null checking

### ISSUE THREAD

**Issue by illuminate3** [vespakoen/menu#107]
I'm sorry to bother you about this since it is more of my lack of knowledge but I would appreciate if you could help.

This works if the db is poplulated with data.
```
		Menu::handler('top')->hydrate( function()
			{
//				$pages = Content::where('print_status_id', '=', 3)->orderBy('order')->get();
			$pages = Content::whereRaw('print_status_id = 3 OR print_status_id = 4')->orderBy('order')->get();
			return $pages;
			},
			function($children, $item)
			{
				if($item->depth < 1) {
					$children->add($item->slug, $item->translate(Config::get('app.locale'))->title, Menu::items($item->as));
				}
			});
```

However, if the db is empty it will error with:
```
Method Illuminate\View\View::__toString() must not throw an exception
```

What would you recommend?

Also, is hydrate a function of Doctrine or php? My google searches are coming up with lots of French ...

Thanks!

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
