### ISSUE TITLE
Active class to parent ul

### ISSUE THREAD

**Issue by basvandertogt** [vespakoen/menu#109]
Hello!

Is it possible to add an extra class to the parent ul when a child is active?

<pre>
<code>
$menu
	->raw('Heading', null, ['class' => 'nav-heading'])
	->add('/', '<em class="icon-speedometer"></em><span>Dashboard</span>')
	->add('#instellingen', '<em class="icon-equalizer"></em><span>Instellingen</span>', Menu::items('instellingen')
		->addClass('nav sidebar-subnav collapse')
		->id('instellingen')
		->add('instellingen/nummerbeheer', '<span>Nummerbeheer</span>')
		->add('instellingen/nummerinstellingen', '<span>Nummerinstellingen</span>'),
		['data-toggle' => 'collapse']
	)
	->add('facturen', '<em class="icon-docs"></em><span>Facturen</span>');
</code>
</pre>

So i want to extend "nav sidebar-subnav collapse" with "active" when "Nummerbeheer" is active.

Regards,
Bas

**Comment by vespakoen** [comment]
Check the following issues:

https://github.com/vespakoen/menu/issues/83
https://github.com/vespakoen/menu/pull/29

You are looking for "setActivePattern" ;)

Let me know if this answers your question.

Ciao!

**Comment by basvandertogt** [comment]
Thank you but that does not what i want.
This does the trick:

<pre>
<code>
// styling
$menu
	->addClass('nav')
	->getAllItems()->map(
		function ($item) {
			if ($item->hasActiveChild()) {
				$item->getChildren()->addClass('in');
			}
		}
);
</code>
</pre>
