### ISSUE TITLE
In what files do we place this code?

### ISSUE THREAD

**Issue by z1haze** [vespakoen/menu#110]
Im not sure in which files we are suppose to place the code to get this up and running..

for example: all of the stuff in here: First, let’s load some pages into the menu. We will do this by utilising the hydrate method.... Where is this supposed to be put? in tinker or something?

**Comment by vespakoen** [comment]
I have not used laravel in a long time, but I guess you are able to make a serviceprovider in which you define your menu's, then register it after registering the menu package.

Let me know if it works out for you

**Comment by nasirkhan** [comment]
@z1haze did you find the solution? I am kind of same position you were in.

**Comment by z1haze** [comment]
I didn't use it. It's obviously not supported anymore xD

**Comment by vespakoen** [comment]
The current way to go about it is making a service provider:

https://laravel.com/docs/5.2/providers

You can add the menu definitions in one of those.

I am still maintaining the package actually, just looking to see if someone is interested in helping out
