### ISSUE TITLE
Different packages used for the same functionality

### ISSUE THREAD

**Issue by moleculezz** [vespakoen/menu#113]
Hi,

I was just browsing and checking out the code and noticed that you are using `Underscore\Methods\StringsMethods::startsWith` and `Illuminate\Support\Str::startsWith` in different classes. While they both do the same thing. Not that it matters because you are including both packages in your project. Just FYI.

**Comment by vespakoen** [comment]
Thanks for the heads up,

I will remove the references to `Illuminate\Support\Str::startsWith` with the next update ;)
