### ISSUE TITLE
Undefined offset: X on getItemListsAtDepth(x)

### ISSUE THREAD

**Issue by erayaydin** [vespakoen/menu#114]
There was a problem with `getItemListsAtDepth(2)`. When reached to this method:

```
Menu::handler('admin')->getItemListsAtDepth(2)->addClass("nav nav-second-level collapse");
```

its make ** ItemList.php line 463** problem

```
Undefined offset: 2
```

Because there is no item lists at depth 2. But this completely stop application. I think its should return empty ItemList

**Comment by vespakoen** [comment]
Interesting, will look into this

**Comment by vespakoen** [comment]
https://github.com/vespakoen/menu/releases/tag/3.0.3

There you go!

**Comment by erayaydin** [comment]
Thank you so much :+1:
