### ISSUE TITLE
Could version 3 support Laravel 4?

### ISSUE THREAD

**Issue by tomzx** [vespakoen/menu#118]
I maintain a project that is currently built on Laravel 4, and uses `vespakoen/menu` ~2.0. However, this means that it will not work under PHP 7 due to some issue in `https://github.com/Anahkiasen/underscore-php` (using a class with name `String` which isn't supported).

Thus, there are a couple of suggested fixes:
- Update the 2.x branch to use `underscore-php` ~2.0 (instead of ~1)
- Add 4.\* dependencies for laravel 4 in composer.json in the 3.x branch (if it is compatible)

Let me know what you think is the most appropriate approach. Thanks!

**Comment by vespakoen** [comment]
Hi, I haven't been using PHP / Laravel in quite a while now, I do accept PR's though.

I would accept a PR where you update the underscore-php dependency, I also welcome maintainers!

**Comment by dmyers** [comment]
This would be great. Laravel 4 has been updated with a patch release for PHP 7 support recently and this package is preventing me from being upgrade my project to it.

**Comment by markcameron** [comment]
@dmyers @vespakoen I forked the repo, and created a `2.x` branch from the `2.0.15` commit. I'm guessing the only way to send a PR is if that branch is created in this repo.

However in the mean time you can add this to you `composer.json` file:

```
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/markcameron/menu"
  }
],
```

and change the `require` for `vespakoen\menu` to:

```
"vespakoen/menu": "2.x-dev",
```

And it will fetch my fork and use that when you run `composer update`

Seems to work fine on my Laravel 4.2 project, at least not more underscore errors.

**Comment by dmyers** [comment]
@markcameron Thanks for sharing. I will give this a shot in a bit and test it out. I appreciate the help!

**Comment by dmyers** [comment]
It worked for me. @vespakoen Could  you make a new branch so that way @markcameron can make a PR?

**Comment by markcameron** [comment]
@dmyers @vespakoen 
Well it doesn't like php 5.3, so I'm wondering if I should tag this as `2.1.0` rather than `2.0.16`to avoid breaking peoples 4.2 composer updates

**Comment by dmyers** [comment]
@markcameron [PHP 5.3 is EOL](http://php.net/supported-versions.php) at this point and [Laravel 4.2 requires](https://laravel.com/docs/4.2#server-requirements) PHP >=5.4 if it helps decide.

**Comment by markcameron** [comment]
@dmyers @vespakoen 
Apologies for the delay, went on holiday that Thursday and was hoping I'd have time to sort it out before I left. I've tagged a version `2.0.16` since 5.3 doesn't apply as you mentioned. Should be good to remove my `"repositories"` walk around now.
