### ISSUE TITLE
Getting an error when I try to composer update

### ISSUE THREAD

**Issue by memco** [vespakoen/menu#30]
When I try to do a composer update on laravel, I often get an error on the post-update artisan optimize:

```
"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Error: Class 'Menu\/MenuServiceProvider' not found in \/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php line 123"
```

Any idea what's causing this and how to fix it?

**Comment by SumitPrajapati** [comment]
when i update command run these error comes. Please suggest

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Illuminate\Routing\ControllerServiceProvider' not found


Script php artisan optimize handling the post-update-cmd event returned with err
or code 255
