### ISSUE TITLE
Question about render performance

### ISSUE THREAD

**Issue by dustingraham** [vespakoen/menu#36]
Have you noticed the call to render being particularly slow? It seems to eat up about 30% of the request time. (300 out of 800 ms on localhost, and 80ms out of 260ms on a test server)

I went to cache the menu after render, but the problem is that doesn't allow the "active" class to be properly applied based on the current route.

I'm considering caching with a cache key that includes the active top level item name, so although I would have 5 or 6 caches of nearly the same menu markup, it would be much faster, and allow the "active" class to be properly appended.

Just wanted to see if you noticed any performance issues with the render, and if there were any other solutions to speed it up.

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
