### ISSUE TITLE
Link isn't marked as active if it leads to "/"

### ISSUE THREAD

**Issue by Cysioland** [vespakoen/menu#64]
As in title. My link leads to a home page, and on said home page it isn't highlighted.

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
