### ISSUE TITLE
Can your menu system work with this kind of menu?

### ISSUE THREAD

**Issue by dragonfire1119** [vespakoen/menu#65]
I've really been liking your menu system and I've been trying to get it to work with this kind of menu

```
<div class="ui menu">
  <a class="active item vt-p">
    <i class="home icon"></i> Home
  </a>
  <a class="item vt-p">
    <i class="mail icon"></i> Messages
  </a>
  <div class="right menu">
    <div class="item">
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
    </div>
  </div>
</div>
```
Your menu system seems like it's only built for unordered lists.

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
