### ISSUE TITLE
How to use your package.

### ISSUE THREAD

**Issue by berpcor** [vespakoen/menu#74]
```php
Menu::handler('main')->hydrate(function()
  {
    return Page::with('translation')
      ->where('group', '=', 'main')
      ->get();
  },
  function($children, $item)
  {
    $children->add($item->translation->slug, $item->translation->name, Menu::items($item->as));
  });
```

You use some 'translation'? Should I have it too? What table structure should I have and what columns should I surely have?

No offense, but your docs are bad, although your package good enough for many cases, I suppose.

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
