### ISSUE TITLE
Ports other than 8000 being cut off URL

### ISSUE THREAD

**Issue by jcomack** [vespakoen/menu#77]
I'm running into an issue when using this package and using Browser Sync.
Whenever I approach the page via the standard localhost:8000 address, everything seems to work just fine. 

However, when using Browser Sync that runs on port 3002, it seems like the package cuts off the port number, resulting in a 404 error when clicking a link. Is there something I'm missing here?

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
