### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by windmaomao** [vespakoen/menu#81]
When calling hydrate method, I couldn't figure out a way to bypass this error, so i digged into code, and found

<code>
    $items = is_callable($resolver) ? $resolver() : $resolver;

    if($items instanceof Collection)
    {
      $items = $items->all();
    }

    $itemsForThisLevel = array_filter($items, function($item) use ($parentId, $parentIdField)
    {
      return $parentId == (is_object($item) ? (isset($item->$parentIdField) ? $item->$parentIdField : 0) : (isset($item[$parentIdField]) ? $item[$parentIdField] : 0));
    });

    foreach($itemsForThisLevel as $item)
    {
      // Let the decorator add the item(s) (and maybe set some attributes)
      $decorator($this, $item);

      // Grab the newest item
      $newestItem = end($this->children);

      // If there is an item, add hydrate it
      if($newestItem)
      {
        // Grab the newest itemlist
        $newestItemList = $newestItem->getChildren();

        // Get the id of the item
        $parentId = is_object($item) ? $item->$idField : $item[$idField];

        // Hydrate the children
        $newestItemList->hydrate($items, $decorator, $idField, $parentIdField, $parentId);
</code>

the last line $items is a bit weird to me, are we adding same set of items again and again to the tree ? 

please help. thanks.

**Comment by Luceos** [comment]
nesting is a xdebug problem configured with php in `/etc/php/conf.d/xdebug.ini` common preference is to increase the nesting level to at least 200 for modern frameworks.

You might have found a solution to the problem in your case, but you simply just reduced the nesting in your application to below 100, once your application increases in complexity you will go past the nest level easily.

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
