### ISSUE TITLE
Set Active For Parent Menu

### ISSUE THREAD

**Issue by fer-ri** [vespakoen/menu#83]
Hi, 

based on my previous code

``` php
Menu::handler('admin')
        ->find('content')
        ->add(route('admin.attachment'), 'Attachments')
        ;
```

It will produce something like this `http://domain.dev/admin/attachments`
It will set as active when we open that url, but how to keep that menu remain active when we open `http://domain.dev/admin/attachments/create` or maybe `http://domain.dev/admin/attachments/1/edit` ?

Thanks :)

**Comment by dmyers** [comment]
@ghprod You rock! :+1: Just found this searching.
