### ISSUE TITLE
Custom Item Structure

### ISSUE THREAD

**Issue by jubairsaidi** [vespakoen/menu#84]
Trying to figure this out for the life of me with no success...

Great Package you have here btw.

Ok so I got the nav on the public side of the site to work just fine, but now I'm trying to get it to work properly in my ajax driven admin CMS.

when I render a list item, each (regardless of if it's a depth 0 or depth 99), it's structure needs to be the following:

```php
<li data-title="{{ $item->title }}" data-id="${{ item->id }}" data-mirrorTarget>
	<div class="row">
		<div class="large-1 columns">
			<i class="fi-list"></i>
		</div>
		<div class="large-11 columns">
			<input type="text" name="nav[${{ item->id }}]" value="{{ $item->title }}" data-mirrorSource="${{ item->id }}">
		</div>
	</div>
	<ol>
		{{-- Sub Nav goes here --}}
	</ol>
</li>
```
So you'll see by this structure, that we have no link tags <a> and obviously a structure of it's own.  Now I can't (don't want to if I can avoid it) use <a> tags because I use them for something else in this instance (granted, i 'could' change that if I absolutely had to).

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
