### ISSUE TITLE
->raw() parameter for $item_element not working as it should.

### ISSUE THREAD

**Issue by jubairsaidi** [vespakoen/menu#85]
only works if you have the default element turned off in your config.  Which is a problem because then all your other elements need to be assigned elements manually rather than simply grab it form the config.  I did find some code somewhere that it said something like "if config value is null then use this value, otherwise use the config value" but I'd have to do a search for it again.

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!

**Comment by vespakoen** [comment]
Seems like this has never worked correctly.
There was even a pull request that tried to fix it:

https://github.com/vespakoen/menu/pull/76/files

Which I even merged, but still does a bad job.

I have fixed the issue now on master, and will make a new tag in a bit
