### ISSUE TITLE
[Feature] Add Raw HTML before/after anchor

### ISSUE THREAD

**Issue by mysteryos** [vespakoen/menu#86]
I was about to use this package to build my menu, when i saw that i will unable to add icons to my menus unless i use the 'raw' function, which rather defeats the purpose of an automated menu generator.

Suggested Functions

```
//Adds HTML before the Anchor element
public function beforeAnchor()

//Adds HTML after the Anchor element
public function afteranchor()
```

Can we please have this feature in the future? It would make the package much more attractive.

**Comment by vespakoen** [comment]
Anyone up for making a PR?

I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it as well!

**Comment by vespakoen** [comment]
Done on master branch, tag coming in a bit
