### ISSUE TITLE
Facades\Config::get() undefined?

### ISSUE THREAD

**Issue by xLink** [vespakoen/menu#87]
using laravel 4.3 i get the following error

Call to undefined method Illuminate\Support\Facades\Config::get() 
on line 221 of vendor/vespakoen/menu/src/Menu/Menu.php

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
