### ISSUE TITLE
Update html-object

### ISSUE THREAD

**Issue by Anahkiasen** [vespakoen/menu#88]
To use `~1.4.0` instead of `~1.2.0`.

**Comment by tiger2wander** [comment]
:+1: 

1.4.* required by other package and caused broken depends. Need update ASAP.

**Comment by Anahkiasen** [comment]
It should just use `~1.4` to avoid these problems in the future, html-object follows semver, there shouldn't be breaking changes between minor releases

**Comment by tiger2wander** [comment]
Yes, better use `~1.4`

**Comment by greabock** [comment]
:+1:  HEY WAKE UP

**Comment by vespakoen** [comment]
Done deal =)
